name: 'Locust Load Test'
author: 'Chris Perry'
description: 'Load Test an application using Locust'
inputs:
  LOCUSTFILE:
    description: 'The locustfile you want to use to load test. If no file is provided, a simple load test will be done on the landing page of the provided URL.'
    required: false
  URL:
    description: 'URL to the site you want to load test. This is Required!'
    required: true
  USERS:
    description: 'Number of Users to spawn. Defaults to 5.'
    required: false
    default: '5'
  RATE:
    description: 'Specify the hatch rate (number of users to spawn per second). Defaults to 5.'
    required: false
    default: '5'
  RUNTIME:
    description: 'Specify the run time for a test. Defaults to 10 seconds.'
    required: false
    default: '10s'
  REPORTPATH:
    description: 'Specify the path to write the HTML report.'
    required: false
    default: 'reports/locust/locust-test-report.html'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.LOCUSTFILE }}
    - ${{ inputs.URL }}
    - ${{ inputs.USERS }}
    - ${{ inputs.RATE }}
    - ${{ inputs.RUNTIME }}
    - ${{ inputs.REPORTPATH }}
branding:
  icon: 'link'
  color: 'green'
